### ISSUE TITLE
Erro na sdk nodejs

### ISSUE THREAD

**Issue by leilaodesatoshi** [thiagozampieri/autentique-v2-nodejs#3]
infelizmente não iremos mais utilizar a authentique

**Comment by thiagozampieri** [comment]
Que erro que aparece?

**Comment by leilaodesatoshi** [comment]
Após adicionar com npm i autentique-v2-nodejs, ao executar a aplicação gera o seguinte erro.

meu código de exemplo

const axios = require('axios')
// const autentique = require('thiagozampieri\autentique-v2-nodejs')

import autentique from 'thiagozampieri\autentique-v2-nodejs'

const api = axios.create({
    baseURL: "https://api.autentique.com.br/v2/graphql",
    Authorization: `Bearer ${process.env.AUTENTIQUE}`
})



module.exports = {
    async create(body) {
        autentique.token = process.env.AUTENTIQUE_TOKEN
        attributes = {
            document: {
                name: 'NOME DO DOCUMENTO'
            },
            signers: [
               {
                   email: body.email_send,
                   action: 'SIGN',
                   positions: [
                       {
                           x: '50', // Posição do Eixo X da ASSINATURA (0 a 100) 
                           y: '80', // Posição do Eixo Y da ASSINATURA (0 a 100)
                           z: '1'   // Página da ASSINATURA
                       },
                       {
                           x: '50', // Posição do Eixo X da ASSINATURA (0 a 100)
                           y: '50', // Posição do Eixo Y da ASSINATURA (0 a 100)
                           z: '2'   // Página da ASSINATURA
                       }
                   ]
               },
               { 
                   email: body.email_sign,
                   action: 'SIGN'
               }
           ],
           file: 'https://www.documento.com.br/Arquivo.pdf'
       };

    autentique.document.create(attributes);
 },
}

erro que gera no nodemon

 /home/node/app/src/services/AutentiqueService.js:4
 import autentique from 'thiagozampieri\autentique-v2-nodejs'
 ^^^^^^

 SyntaxError: Cannot use import statement outside a module
     at compileFunction (<anonymous>)
     at Object.compileFunction (node:vm:352:18)
     at wrapSafe (node:internal/modules/cjs/loader:1025:15)
     at Module._compile (node:internal/modules/cjs/loader:1059:27)
     at Object.Module._extensions..js (node:internal/modules/cjs/loader:1147:10)
     at Module.load (node:internal/modules/cjs/loader:975:32)
     at Function.Module._load (node:internal/modules/cjs/loader:822:12)
     at Module.require (node:internal/modules/cjs/loader:999:19)
     at require (node:internal/modules/cjs/helpers:102:18)
     at Object.<anonymous> (/home/node/app/src/controllers/AutentiqueController.js:1:27)
     at Module._compile (node:internal/modules/cjs/loader:1095:14)
     at Object.Module._extensions..js (node:internal/modules/cjs/loader:1147:10)
     at Module.load (node:internal/modules/cjs/loader:975:32)
     at Function.Module._load (node:internal/modules/cjs/loader:822:12)
     at Module.require (node:internal/modules/cjs/loader:999:19)
     at require (node:internal/modules/cjs/helpers:102:18)

 Node.js v17.0.1
 [nodemon] app crashed - waiting for file changes before starting...


Quando eu uso o require dá o mesmo erro pensei que era o caminho que estava errado thiagozampieri\autentique-v2-nodejs remove o thiagozampieri\ aí mesmo erro.

**Comment by thiagozampieri** [comment]
`npm i autentique-v2-nodejs`
para instalar é assim que é realizado e depois vc importa 
`
const autentique = require('autentique-v2-nodejs');`

**Comment by leilaodesatoshi** [comment]
Bom dia, fiz igual como vc indicou mais nao funciona gera o erro de const fala para usar o import.

**Comment by leilaodesatoshi** [comment]
/usr/src/app/src/services/AutentiqueService.js:8
const autentique = require('autentique-v2-nodejs');
                   ^
LDS_CONTAINER  |
Error [ERR_REQUIRE_ESM]: require() of ES Module /usr/src/app/node_modules/autentique-v2-nodejs/dist/index.js from /usr/src/app/src/services/AutentiqueService.js not supported.
index.js is treated as an ES module file as it is a .js file whose nearest parent package.json contains "type": "module" which declares all .js files in that package scope as ES modules.
Instead rename index.js to end in .cjs, change the requiring code to use dynamic import() which is available in all CommonJS modules, or change "type": "module" to "type": "commonjs" in /usr/src/app/node_modules/autentique-v2-nodejs/package.json to treat all .js files as CommonJS (using .mjs for all ES modules instead).
LDS_CONTAINER  |
    at Object.<anonymous> (/usr/src/app/src/services/AutentiqueService.js:8:20)
    at Object.<anonymous> (/usr/src/app/src/controllers/AutentiqueController.js:1:27)
    at Object.<anonymous> (/usr/src/app/src/routes/autentique.routes.js:3:30)
    at Object.<anonymous> (/usr/src/app/index.js:41:9) {
  code: 'ERR_REQUIRE_ESM'
}
LDS_CONTAINER  |
Node.js v17.0.1
[nodemon] app crashed - waiting for file changes before starting...
